### ISSUE TITLE
Include pre-commit hook to verify standards compliancy

### ISSUE THREAD

**Issue by lietu** [digitalliving/standards#20]
Travis runs `openapi-validator --path draft -v IhanStandardsValidator`, we should make this be run automatically by `pre-commit`.

Similarly contents of `travis-validation.sh` should be moved to be a part of `pre-commit` configuration and cross-platform compatible.

**Comment by fbjorn** [comment]
Standards validation is covered by #21 

For executable files created [separate issue](https://github.com/digitalliving/standards/issues/22)
